### ISSUE TITLE
v0.1.0-alpha.1 being detected as a Trojan

### ISSUE THREAD

**Issue by Rumik** [ClassicOldSong/Apollo#21]
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AScript%2FWacatac.B!ml&threatid=2147735503

I'm on a work PC so I can't allow it. 

Can anything be done?

**Comment by ClassicOldSong** [comment]
The binary is not digital signed. A digital signature for a binary costs money to prove you're "safe", just because you gave them money.

Windows tends to mark unknown exes as a Trojan, assigning a scary looking random name for them no matter they're actually safe or not. Even a simple Hello World can be marked as a Trojan.

https://stackoverflow.com/questions/62364507/compiled-c-executable-is-detected-as-a-virus-by-windows-defender

You can always check with any other antivirus software to see if it's safe.

There're many signed malware that actually does harm to your computer are ignored by Windows Defender, so sometimes it's just BS.

**Comment by aefesp** [comment]
The below still costs money but it looks as though you can apply for Trusted Signing as an individual using Azure now for $9.99 a month. 

https://melatonin.dev/blog/code-signing-on-windows-with-azure-trusted-signing/

**Comment by FallingSnow** [comment]
Not sure if you know of [SignPath](https://signpath.org/) and have any interest. Seems to be what's used by MTT with the [Virtual Drivers](https://github.com/VirtualDrivers/Virtual-Audio-Driver) he makes. Never used it personally though.
