### ISSUE TITLE
I have some questions..

### ISSUE THREAD

**Issue by yahyatube** [ClassicOldSong/Apollo#29]
First, I want to express my gratitude for your incredible effort. This program is truly wonderful and adds a fantastic feature for game broadcasting.

I have a few questions. I’m not a programmer, but I’m looking for a solution to broadcast games, and I have several goals in mind.

1- Will it be possible to stream games to the browser in the future, similar to what this site offers: [https://demo.clastr.net/](url)

2- I want to broadcast my own game, which is an online game designed for Windows. Can I make it playable on Android devices for multiple phones simultaneously on the same Apollo server? Additionally, there's an issue where if a player exits and leaves their broadcast, the game continues running, and if another player logs in, they access the first player's account. This causes a problem.

3- How can I protect my system files on a Windows host

I understand that this server is designed for internal broadcasting, but I want to make it public so people can use my PC to play my game. Is this possible? The game is lightweight and doesn’t consume many resources.

Finally, I want to commend you on this fantastic project. Your work is truly impressive and reflects a high level of dedication and skill. It’s clear that you have a passion for what you do, and I believe this project has the potential to make a significant impact. Keep up the excellent work!, and I hope you continue developing more amazing projects in the future :)

**Comment by ClassicOldSong** [comment]
Thanks for your appreciation, but Apollo, together with Sunshine and other game streaming solutions, are not meant to "broadcast" video streams. They work similarly but differs subtally.

1. Stream to browsers are not planned at least for now, since browsers don't accept raw TCP/UDP streams for low-latency video streaming.

2. Multi-player is available but they won't work as you expected: all players connected to the same stream are actually operating the same set of controller/mouse/keyboard or whatever your input device. They can't have separated accounts.

3. Don't pair your computer with any strangers.

If you want to broadcast, you can try some more dedicated softwares like [OBS](https://github.com/obsproject/obs-studio).

**Comment by yahyatube** [comment]
Thank you for your response.

no no i don't mean OBS, I understand you, I'm not looking for streaming games as a video

I tried your software, and it's exactly what I needed for my use, In fact I'm using it right now, your program solves a big problem for me and I am currently using the latest version.

-------------

When I used it, I started thinking about creating something similar to a cloud game service, I have a simple game that I own and is programmed to run on Windows so I just wanted to allow players to access it via Android without risking my windows. I have seen many applications that do this, such as Netboom app and Starparks app Which runs as a cloud gaming service. I don't know how they allow each person to use the same game separately, or maybe they provide a virtual server for each person

if you have time can you check this for using the browser: [https://www.youtube.com/watch?v=4zTkvasOGkY](url)
also this for ubuntu: [https://www.youtube.com/watch?v=RUoZvhtun7U&t=80s](url) (This is exactly what I'm looking for)

I was using Rainway, They somehow had the games run via browser and unfortunately it has stopped.

It's good to have your program now, I hope you help more people and your program is very useful 🥇 

I apologize for the length of the text...

**Comment by ClassicOldSong** [comment]
They've invested lots of money for virtual machines and actual hardware to run the cloud gaming service.

Stream to browsers is not planned now and I have explained why in the previous reply.

It's actually doable, but those companies pay their employees to implement a dedicated service that stream games to browsers directly, and the start up fee you need to get the machines setup, internet service ready are already beyond what you can imagine, no to mention the maintenance costs coming after.

And these kind of services don't make money, that's why the previous service you like stopped.

**Comment by yahyatube** [comment]
Thank you and I look forward to more of your work :)
