### ISSUE TITLE
run two game at the same time is not work

### ISSUE THREAD

**Issue by yybfrank** [ClassicOldSong/Apollo#67]
I want to run multiple Apollo instances and playing two game at the same time,how to implement it? is Apollo support that?

**Comment by ClassicOldSong** [comment]
As my previouse explaination, both Sunshine and Apollo can not do this. What you're looking for is [Duo](https://github.com/DuoStream/Duo), which is not free for normal usage and has its own limitations.

**Comment by Matszwe02** [comment]
I would love for this feature to be on the roadmap, as it would allow users to create their own gaming servers and make a lan party (or localhost party :D ) with only one pc. If I understand correctly, duo only does one thing differently, which is running the app on another virtual desktop. I know that's a very uncommon scenario, but I'm looking forward for it to be implemented

**Comment by kayti** [comment]
DUO is utilising hacks around Windows, which break with Windows updates. At the same time, it is also breaking Windows license terms (only specific, enterprise and server licenses allow multiple users at the same time). 

So it is better if it is a separate project, at least no need to worry that remote access through it will stop working after an update. In theory, DUO maintainer said something in the past about implementing Apollo into DUO as an alternative to pure sunshine, but didn't hear anything about that since then.

**Comment by Matszwe02** [comment]
> DUO is utilising hacks around Windows, which break with Windows updates. At the same time, it is also breaking Windows license terms (only specific, enterprise and server licenses allow multiple users at the same time).
> 
> So it is better if it is a separate project, at least no need to worry that remote access through it will stop working after an update. In theory, DUO maintainer said something in the past about implementing Apollo into DUO as an alternative to pure sunshine, but didn't hear anything about that since then.

Ok, that clears my suggestion. Too bad linux version won't be running similarly smooth anytime soon...
Also, would it be possible to just run apollo on user created virtual desktops and then use it with this feature, or executing it like that is blocked by Microslop? With that approach the individual user that runs these instances will be breaking the license, not Apollo, am I correct?
