### ISSUE TITLE
Check your firewall and port forwarding rules for ports: UDP 47998 and UDP 48000

### ISSUE THREAD

**Issue by yahyatube** [ClassicOldSong/Apollo#71]
This problem caused me great inconvenience I tried everything, I disabled the firewall, I tried changing the screen size, and I tried many attempts and they all failed (sometimes the login occurs and sometimes the error appears repeatedly and I cannot log in)

I even tried Sunshine and the same problem occurs. There is no Geforce Game Stream and no firewall. I tried adjusting the screen size and disabling any other graphics card driver and the problem still persists.

**Comment by ClassicOldSong** [comment]
Which network are your devices on? Are they on the same network or over some other networks?

Please describe your network hierarchy you're using for your computer and clients as detailed as possible.

Also the default ports for streaming are 47984 and 47989, 47989 and 48000 are used for service discovery and configuration. If you adjust your ports too close to these numbers, their functionalities might get overlapped with other instances. Are you running multiple instances of Apollo/Sunshine? If so please change the ports for your instances to more separated numbers, like 46989 and 48989.

**Comment by yahyatube** [comment]
the error:
Check your firewall and port forwarding rules for ports: UDP 47998 and UDP 48000

this show that there is an issue when choice the monitor i think:
[https://www.reddit.com/r/MoonlightStreaming/comments/13ydk6v/sunshine_giving_check_your_firewall_and_port/](url)

the network:
Two computers connected together by a cable Very simple, without anything, because I was suspicious of the router, so I connected it directly to the computer

The problem, I think, is when choosing the graphics card or screen size. I don’t know. I read some topics about the matter and was unable to solve the problem (the server works sometimes and sometimes it doesn’t and some time only black screen).

**Comment by ClassicOldSong** [comment]
Windows requires some really nasty settings to connect two computers directly with an Ethernet cable, this might be one of the problems.

If you're using a computer with multiple graphics card, generally you should enable Headless Mode in Apollo. Due to how Windows applications select their GPU preferences, when you first stream from a monitor connected to graphics card A, you cannot then stream from monitor connected to graphics card B without restarting the program. Headless mode forces all sessions to use virtual display, and that avoids the issue that users might stream from different gpus unconsciously.

PS: GitHub uses Markdown for formatting its content everywhere, it's not the same as BB Code or some format from other forums. If you don't know how to write Markdown, just leave urls in plain text. Wrong format will make the link inaccessible by clicking it directly.

**Comment by yahyatube** [comment]
Sure, I'll give it a try today. I've also updated the link—thanks for pointing that

**Comment by yahyatube** [comment]
thanks it work!

i write a topic about it if someone need help to fix it:

https://www.techofflimits.com/how-to-fix-sunshine-check-your-firewall-and-port-forwarding-rules-for-ports-udp-47998-and-udp-48000-for-moonlight/

**Comment by ClassicOldSong** [comment]
You don't need to install that virtual display driver with Apollo. Apollo has its built-in virtual display and won't use the one you installed separately.
