### ISSUE TITLE
Disabling display doesn't work.

### ISSUE THREAD

**Issue by d4maniac** [ClassicOldSong/Apollo#81]
Hello and thanks for this great fork!

Windows 10
Main PC has a RTX4090:
Hdmi port 1 to TV/Main display 4k 120hz
DP 1 to Gaming Screen (usually turned off)
DP 2 to capture device - This capture device only does 1080p á 140 hz-

Nvidia is used to clone and scale output from HDMI 1 to DP 2 so basically I can stream to this device for live content.

I am using Apollo + Artemis on a Nvidia shield in the living room. Set to use virtual display on start up, which works great. However I cannot disable the primary physical monitor. It accepts me disabling it (as per your FAQ) but as soon as I get the choice of keeping or reverting the changes the screen gets reenabled regardless of the choice made.

This means I always have to active displays during usage with Artemis (one virtual and one physical) which is less ideal.

Any suggestions on what I could do to solve this?

**Comment by ClassicOldSong** [comment]
There're multiple possibilities:

1. Monitor itself thinks it's disconnected so it cuts its own power and Windows thinks there's a configuration change so it reverts to a previous configuration (happens a lot on my previous monitor and I have to change the monitor to solve this problem since it'll wake my PC up instantly after it goes to sleep)

2. Something is waking your monitor, maybe your capture software

3. Windows acting dumb, try clearing the configuration cache as described in the FAQ 

In this case I think you might need to disable both your primary display(HDMI) and the streaming capture output(DP2). Apollo won't enable your physical display as there's no code doing that inside.

**Comment by ClassicOldSong** [comment]
Any updates?
