### ISSUE TITLE
New feature release time

### ISSUE THREAD

**Issue by ZhaoZelin2000** [ClassicOldSong/Apollo#9]
New feature release
I am eagerly looking forward to using these new features and would greatly appreciate it if the author could provide an approximate release date. I truly value the effort put into making streaming easier. Additionally, I was wondering if the author might be interested in developing clipboard synchronization and file transfer capabilities, as these would be extremely practical for office work。
1.Built in virtual monitor support (Windows driver development is currently underway)
2.Multi monitor stream from an instance
3.Provide better audio routing for multi monitor solutions
4.Touchpad input simulation
5.UI rewriting

**Comment by ClassicOldSong** [comment]
This is a very complicated and time consuming process, just to filter through the original spaghetti code.

Release time can't be guaranteed but there should be a preview build regarding virtual display coming soon.

**Comment by ClassicOldSong** [comment]
Here's a preview version of Apollo: https://github.com/ClassicOldSong/Apollo/releases/tag/apollo-0.0.0-preview

**Comment by ZhaoZelin2000** [comment]
Do I need to uninstall the previous Sunshine and parsec vdd

**Comment by ClassicOldSong** [comment]
You don't. Instructions are well written in the release page.

**Comment by drajabr** [comment]
@ZhaoZelin2000 I'm now running 3 instances of apollo, and for audio routing I recommend the following setup temporary:

1. Install virtual audio software (such as AB Cable) but I ended up using (VAC for one interface control of the 3 virtual cables)
2. Create virtual audio devices as much as displays you have (I have 3, so created "Left, Right, Bottom" named audio devices)
3. Configure each instance to use "Audio Sink" the corrosponding one.
4. I use "soundswitch" to force default output on speaker only
5. I use windows settings to route specfic apps to each intended display by its corrosponding virtual device
6. In the browser, I have the option to route audio to specfic output for each tab by using "AudioPick" extension

This is my setup, its reliable, one little caveat is, I can't get volume control of each virtual device to work, but anyway I use hardware volume buttons on the client (side hint I use precise volume control on android to make the volume steps 4 steps only 0 25% 50% 100% because I don't want to keep pressing the volume button to increase or decrease the audio) . 
Sorry for typos, English is not my mother tongue.
