### ISSUE TITLE
Linux build

### ISSUE THREAD

**Issue by drajabr** [ClassicOldSong/Apollo#96]
Can't wait to nuke my windows installation ;)

**Comment by ClassicOldSong** [comment]
Just tried to make some progress in Linux but the situation is way much worse than Windows. Things are a total mess in Linux's capturing API, and currently feasible virtual display solution wastes way too much performance, and due to how Linux's display system are implemented, a Windows like VDD solution is near impossible.

**Comment by jfly** [comment]
> currently feasible virtual display solution wastes way too much performance 

@ClassicOldSong, just curious, is this referring to `evdi`? Is there an ongoing discussion somewhere about this performance issue?

**Comment by ClassicOldSong** [comment]
Linux's architecture decided that the dummy display's framebuffer needs to be on your DRAM, as they're not reported by your GPU driver so they cannot use VRAM...

**Comment by jfly** [comment]
Sorry, I don't fully understand this. Is this architectural issue something the `evdi` folks have run into? Are there discussion on `evdi`, or the LKML about a kernel patch to resolve the issue?

**Comment by ClassicOldSong** [comment]
It is DRM's issue, not something a kernel patch can resolve. Even if, it'll be way too hacky for users to do it themselves.

Or we need to give up Xserver users, it seems Wayland handles this better, but still might not be ideal.

**Comment by jfly** [comment]
I'd love to understand the details here. Is there a writeup somewhere?

**Comment by ClassicOldSong** [comment]
This is the write up. A write up concludes technical details just like this.

**Comment by xrishox** [comment]
x11 is a dead protocol in maintenance mode. it is a series of hacks built on top of hacks dating back to the 80s. wayland is the present and the future.

**Comment by jfly** [comment]
> It is DRM's issue, not something a kernel patch can resolve

I'm confused: how could this be possible on Windows, but a patch to the Linux kernel couldn't resolve the issue?

Is this problem something the [wolf](https://github.com/games-on-whales/wolf) folks have addressed? Or are they just living with the issue?

**Comment by ClassicOldSong** [comment]
DRM here is Direct Rendering Manager, the display framework of Linux, not Digital Rights Management. There is no way to implement a universal virtual display on DRM because of its architecture. That's why the AMDGPU driver has its own virtual display implementation, and that's totally out of what Apollo can control.

Wolf only supports Wayland, and their implementation is actually less than ideal (gstreamer as middleware causing increased latency and some other issues)

Even with native real display, Linux doesn't seem to be able to provide on demand frame capture, causing constant GPU encoding load and constant bandwidth usage no matter whether there're changes on the screen.

If we can ditch DRM, there're possibilities to make it work like on Windows, but now pretty much everything is based on DRM so that's impossible. And Linux isn't that "free" as you imagined, maintainers can reject your very valid commits without any reason.

Also, doing all these requires vast amounts of time and effort, and nobody is even paying for our living if we decide to work on this fundamental breaking changes.

I suggest you do some research first before asking with all "I don't understand" waiting for someone has replied to you already claiming it's hard and impractical. Explaining technical details is very difficult and tedious, especially to people who don't have technical backgrounds, each detail can introduce a dozen of new details awaiting for explanation.

Or if you can come up with practical solutions to this problem, either from programming perspective or persuading kernel maintainers to accept changes to this direction, or provide financial support for people who can solve the problem, you're always welcomed.

Linux for gaming, even for daily usage, is still far far from ideal for ordinary users.

**Comment by Zerwin** [comment]
Excluding Virtual Displays for now, could maybe this tool https://git.dec05eba.com/gpu-screen-recorder/about/ help with performance of recording on Linux ? From the claims and some quick testing on my PC, the performance impact was negligible. That would allow sidestepping a vast amount of time and effort needed to implement a capture method on Linux.

**Comment by ClassicOldSong** [comment]
Screen recordings and streaming to stream platforms are not latency sensitive, but game streaming is. That's a important part of what Linux currently lags behind.

**Comment by tiagomta** [comment]
Any news about linux porting? Even without virtual display, I would like to have the other functionallities in linux :(

**Comment by Halle914** [comment]
Honestly, I just want to get away from Sunshine and use your client instead. Its literally the only thing I miss about windows now that I have made the move to Fedora. 

Otherwise, great work ClassicOldSong. You're doing amazing things.
